# Travis CI build file for KituraKit.

sudo: required
branches:
  only:
    - master
    - develop
    - feature

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - echo "Done1"

jobs:
    include:
      - stage: Update
        if: type = push
        script: ci/update.sh
        
      - stage: Release
        if: branch = master
        script: ci/release.sh
        
