# Travis CI build file for KituraKit.

sudo: required
branches:
  only:
    - master
    - develop
    - feature

os:
- linux
- osx
dist: trusty

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - echo "Done"

jobs:
    include:
      - stage: Update
        if: type = push AND branch = master AND platform = Linux
        script: ci/update.sh
        
      - stage: Release
        if: type = push AND branch = master AND platform = Linux
        script: ci/release.sh
        
