# Travis CI build file for KituraKit.

sudo: required
branches:
  only:
    - master
    - develop
    - feature

os:
- linux
- osx
dist: trusty
osx_image: xcode9.2

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

jobs:
    include:
      - stage: Update
        if: type = push AND branch = master AND platform = Linux
        script: ci/update.sh
        
      - stage: Release
        if: type = push AND branch = master AND platform = Linux
        script: ci/release.sh
        
